#ifndef HTMLFILE_H
#define HTMLFILE_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>


static const char HTTP_RESPONSE_BODY_TEMPLATE[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    " <meta charset=\"UTF-8\">\n"
    " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    " <title>Pico W Control Center</title>\n"
    " <style>\n"
    " * { box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; }\n"
    " body { background-color: #f4f6f9; margin: 0; padding: 20px; color: #333; }\n"
    " .container { max-width: 500px; margin: 0 auto; background: #ffffff; padding: 25px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }\n"
    " h2 { margin-top: 0; font-size: 1.4rem; color: #1e293b; text-align: center; }\n"
    " label { display: block; font-weight: 600; margin-bottom: 6px; font-size: 0.9rem; color: #475569; }\n"
    " select, input[type=\"text\"], input[type=\"number\"], input[type=\"range\"] {\n"
    " width: 100%; padding: 10px; margin-bottom: 15px; border: 1px solid #cbd5e1; border-radius: 6px; font-size: 0.95rem;\n"
    " }\n"
    " .panel { display: none; margin-top: 15px; padding-top: 15px; border-top: 1px solid #e2e8f0; }\n"
    " .active { display: block; }\n"
    " button {\n"
    " width: 100%; padding: 12px; background-color: #2563eb; color: white; border: none;\n"
    " border-radius: 6px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: background 0.2s; margin-bottom: 10px;\n"
    " }\n"
    " button:hover { background-color: #1d4ed8; }\n"
    " button:active { background-color: #1e40af; }\n"
    " .status-msg { margin-top: 15px; padding: 10px; border-radius: 6px; font-size: 0.85rem; text-align: center; display: none; }\n"
    " .success { background-color: #dcfce7; color: #166534; }\n"
    " .error { background-color: #fee2e2; color: #991b1b; }\n"
    " .color-box { width: 100%; height: 50px; border-radius: 6px; margin-bottom: 15px; border: 1px solid #cbd5e1; }\n"
    " .rgb-text { text-align: center; font-weight: 600; margin-bottom: 15px; color: #475569; }\n"
    " </style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"container\">\n"
    " <h2>Pico W Control Panel</h2>\n"
    " <label for=\"panelSelect\">Select Mode:</label>\n"
    " <select id=\"panelSelect\" onchange=\"switchPanel(this.value)\">\n"
    " <option value=\"single\">Single Colour</option>\n"
    " <option value=\"custom\">Custom Colour</option>\n"
    " <option value=\"multi\">Multi-Zone Colour</option>\n"
    " <option value=\"dual\">Dual-Zone Colour</option>\n"
    " <option value=\"crossfade\">Crossfade</option>\n"
    " <option value=\"corner\">Corners</option>\n"
    "<option value=\"flicker\">Flicker</option>\n"
    " <option value=\"effects\">Effects</option>\n"
    " </select>\n"
    " <div id=\"single\" class=\"panel active\">\n"
    " <label for=\"mbColour\">LED Colour:</label>\n"
    " <select id=\"mbColour\">\n"
    " <option value=\"0x00\">Cyan</option>\n"
    " <option value=\"0x01\">Purple</option>\n"
    " <option value=\"0x02\">Blue</option>\n"
    " <option value=\"0x03\">Midnight Blue</option>\n"
    " <option value=\"0x05\">Bright Purple</option>\n"
    " <option value=\"0x06\">Lavender</option>\n"
    " <option value=\"0x08\">Pink</option>\n"
    " <option value=\"0x0F\">Yellow / Orange</option>\n"
    " <option value=\"0x10\">Off Yellow</option>\n"
    " <option value=\"0x12\">Lime</option>\n"
    " <option value=\"0x13\">Orange</option>\n"
    " <option value=\"0x14\">Red / Orange</option>\n"
    " <option value=\"0x15\">Red</option>\n"
    " <option value=\"0x19\">Green</option>\n"
    " <option value=\"0x1A\">Lime Green</option>\n"
    " <option value=\"0x1B\">White</option>\n"
    " <option value=\"0x1D\">Off</option>\n"
    " <option value=\"0x1F\" selected>Random</option>\n"
    " </select>\n"
    " <label for=\"vibPattern\">Vibration Pattern:</label>\n"
    " <select id=\"vibPattern\">\n"
    " <option value=\"0x0\">None (Off)</option>\n"
    " <option value=\"0x1\">Short (S)</option>\n"
    " <option value=\"0x2\">Short - Short (S-S)</option>\n"
    " <option value=\"0x3\">Short x3 (S-S-S)</option>\n"
    " <option value=\"0x4\">Short - Short - Medium (S-S-M)</option>\n"
    " <option value=\"0x5\">Short x4 - Medium - Short (S4-M-S)</option>\n"
    " <option value=\"0x6\">Short x3 - Medium x3 - Short x3 (S3-M3-S3)</option>\n"
    " <option value=\"0x7\">Extra Long (XL)</option>\n"
    " <option value=\"0x8\">Extra Short x6 (XS6)</option>\n"
    " <option value=\"0x9\">Short Alternate (S-ALT)</option>\n"
    " <option value=\"0xA\">Medium (M)</option>\n"
    " <option value=\"0xB\">Long (L)</option>\n"
    " </select>\n"
    " <label for=\"ledMask\">LED Mask (Position):</label>\n"
    " <select id=\"ledMask\">\n"
    " <option value=\"0x00\">All LEDs</option>\n"
    " <option value=\"0x20\">Top Right Only</option>\n"
    " <option value=\"0x40\">Bottom Right Only</option>\n"
    " <option value=\"0x60\">Bottom Left Only</option>\n"
    " <option value=\"0x80\">Top Left Only</option>\n"
    " </select>\n"
    " <button onclick=\"submitSingle()\">Send Command</button>\n"
    " <button onclick=\"OFF()\">OFF</button>\n"
    " <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"

    " <div id=\"multi\" class=\"panel\">\n"
    "   <h2>[ Multi-Zone Colour Controls ]</h2>\n"

    "   <label for=\"multiCentre\">Centre Colour:</label>\n"
    "   <select id=\"multiCentre\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"multiTopLeft\">Top Left Colour:</label>\n"
    "   <select id=\"multiTopLeft\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"multiTopRight\">Top Right Colour:</label>\n"
    "   <select id=\"multiTopRight\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"multiBottomLeft\">Bottom Left Colour:</label>\n"
    "   <select id=\"multiBottomLeft\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"multiBottomRight\">Bottom Right Colour:</label>\n"
    "   <select id=\"multiBottomRight\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"multiVib\">Vibration:</label>\n"
    "   <select id=\"multiVib\">\n"
    "     <option value=\"0x00\">None (Off)</option>\n"
    "     <option value=\"0x01\">Short (S)</option>\n"
    "     <option value=\"0x02\">Short - Short (S-S)</option>\n"
    "     <option value=\"0x03\">Short x3 (S-S-S)</option>\n"
    "     <option value=\"0x04\">Short - Short - Medium</option>\n"
    "     <option value=\"0x05\">Short x4 - Medium - Short</option>\n"
    "     <option value=\"0x06\">Short x3 - Medium x3 - Short x3</option>\n"
    "     <option value=\"0x07\">Extra Long (XL)</option>\n"
    "     <option value=\"0x08\">Extra Short x6 (XS6)</option>\n"
    "     <option value=\"0x09\">Short Alternate (S-ALT)</option>\n"
    "     <option value=\"0x0A\">Medium (M)</option>\n"
    "     <option value=\"0x0B\">Long (L)</option>\n"
    "   </select>\n"

    "   <button onclick=\"submitMultiColour()\">Fill Multi-Colour</button>\n"
    " <button onclick=\"OFF()\">OFF</button>\n"
    " <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"



     " <div id=\"flicker\" class=\"panel\">\n"
    "   <h2>[ Flicker Colour Controls ]</h2>\n"

    "   <label for=\"flickerCentre\">Centre Colour:</label>\n"
    "   <select id=\"flickerCentre\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"flickerTopLeft\">Top Left Colour:</label>\n"
    "   <select id=\"flickerTopLeft\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"flickerTopRight\">Top Right Colour:</label>\n"
    "   <select id=\"flickerTopRight\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"flickerBottomLeft\">Bottom Left Colour:</label>\n"
    "   <select id=\"flickerBottomLeft\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"flickerBottomRight\">Bottom Right Colour:</label>\n"
    "   <select id=\"flickerBottomRight\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"flickerVib\">Vibration:</label>\n"
    "   <select id=\"flickerVib\">\n"
    "     <option value=\"0x00\">None (Off)</option>\n"
    "     <option value=\"0x01\">Short (S)</option>\n"
    "     <option value=\"0x02\">Short - Short (S-S)</option>\n"
    "     <option value=\"0x03\">Short x3 (S-S-S)</option>\n"
    "     <option value=\"0x04\">Short - Short - Medium</option>\n"
    "     <option value=\"0x05\">Short x4 - Medium - Short</option>\n"
    "     <option value=\"0x06\">Short x3 - Medium x3 - Short x3</option>\n"
    "     <option value=\"0x07\">Extra Long (XL)</option>\n"
    "     <option value=\"0x08\">Extra Short x6 (XS6)</option>\n"
    "     <option value=\"0x09\">Short Alternate (S-ALT)</option>\n"
    "     <option value=\"0x0A\">Medium (M)</option>\n"
    "     <option value=\"0x0B\">Long (L)</option>\n"
    "   </select>\n"

    "<div class='slidecontainer'>"
    "<input type='range' min='1' max='255' value='50' class='slider' id='flickermyRange'>"
    "</div>"

    "   <button onclick=\"submitFlickerColour()\">Fill Flicker-Colour</button>\n"
    " <button onclick=\"OFF()\">OFF</button>\n"
    " <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"


    " <div id=\"crossfade\" class=\"panel\">\n"
    "   <h2>[ Crossfade Controls ]</h2>\n"

    "   <label for=\"CrossfadeColourA\">Colour A:</label>\n"
    "   <select id=\"CrossfadeColourA\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"CrossfadeColourB\">Colour B:</label>\n"
    "   <select id=\"CrossfadeColourB\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"CrossfadeVib\">Vibration:</label>\n"
    "   <select id=\"CrossfadeVib\">\n"
    "     <option value=\"0x00\">None (Off)</option>\n"
    "     <option value=\"0x01\">Short (S)</option>\n"
    "     <option value=\"0x02\">Short - Short (S-S)</option>\n"
    "     <option value=\"0x03\">Short x3 (S-S-S)</option>\n"
    "     <option value=\"0x04\">Short - Short - Medium</option>\n"
    "     <option value=\"0x05\">Short x4 - Medium - Short</option>\n"
    "     <option value=\"0x06\">Short x3 - Medium x3 - Short x3</option>\n"
    "     <option value=\"0x07\">Extra Long (XL)</option>\n"
    "     <option value=\"0x08\">Extra Short x6 (XS6)</option>\n"
    "     <option value=\"0x09\">Short Alternate (S-ALT)</option>\n"
    "     <option value=\"0x0A\">Medium (M)</option>\n"
    "     <option value=\"0x0B\">Long (L)</option>\n"
    "   </select>\n"

    "<div class='slidecontainer'>"
    "<input type='range' min='1' max='255' value='50' class='slider' id='myRange'>"
    "</div>"

    "   <button onclick=\"submitCrossfade()\">Fill Crossfade</button>\n"
    " <button onclick=\"OFF()\">OFF</button>\n"
    " <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"

    " <div id=\"dual\" class=\"panel\">\n"
    "   <h2>[ Dual Colour Controls ]</h2>\n"

    "   <label for=\"dualCentre\">Centre Colour:</label>\n"
    "   <select id=\"dualCentre\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"dualOuter\">Outer Colour:</label>\n"
    "   <select id=\"dualOuter\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"dualVib\">Vibration:</label>\n"
    "   <select id=\"dualVib\">\n"
    "     <option value=\"0x00\">None (Off)</option>\n"
    "     <option value=\"0x01\">Short (S)</option>\n"
    "     <option value=\"0x02\">Short - Short (S-S)</option>\n"
    "     <option value=\"0x03\">Short x3 (S-S-S)</option>\n"
    "     <option value=\"0x04\">Short - Short - Medium</option>\n"
    "     <option value=\"0x05\">Short x4 - Medium - Short</option>\n"
    "     <option value=\"0x06\">Short x3 - Medium x3 - Short x3</option>\n"
    "     <option value=\"0x07\">Extra Long (XL)</option>\n"
    "     <option value=\"0x08\">Extra Short x6 (XS6)</option>\n"
    "     <option value=\"0x09\">Short Alternate (S-ALT)</option>\n"
    "     <option value=\"0x0A\">Medium (M)</option>\n"
    "     <option value=\"0x0B\">Long (L)</option>\n"
    "   </select>\n"

    "   <button onclick=\"submitDualColour()\">Fill Dual-Colour</button>\n"
    " <button onclick=\"OFF()\">OFF</button>\n"
    " <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"

    " <div id=\"custom\" class=\"panel\">\n"
    "   <h2>[ Custom RGB Controls ]</h2>\n"
    "   <div id=\"colorBox\" class=\"color-box\"></div>\n"

    "   <div class=\"slider-group\">\n"
    "     <label for=\"red\">Red: <span id=\"redVal\">128</span></label>\n"
    "     <input type=\"range\" id=\"red\" min=\"0\" max=\"255\" value=\"128\">\n"
    "   </div>\n"

    "   <div class=\"slider-group\">\n"
    "     <label for=\"green\">Green: <span id=\"greenVal\">128</span></label>\n"
    "     <input type=\"range\" id=\"green\" min=\"0\" max=\"255\" value=\"128\">\n"
    "   </div>\n"

    "   <div class=\"slider-group\">\n"
    "     <label for=\"blue\">Blue: <span id=\"blueVal\">128</span></label>\n"
    "     <input type=\"range\" id=\"blue\" min=\"0\" max=\"255\" value=\"128\">\n"
    "   </div>\n"

    "   <div id=\"rgbValue\" class=\"rgb-text\">rgb(128, 128, 128)</div>\n"

    "   <label for=\"CustomVib\">Vibration:</label>\n"
    "   <select id=\"CustomVib\">\n"
    "     <option value=\"0x00\">None (Off)</option>\n"
    "     <option value=\"0x01\">Short (S)</option>\n"
    "     <option value=\"0x02\">Short - Short (S-S)</option>\n"
    "     <option value=\"0x03\">Short x3 (S-S-S)</option>\n"
    "     <option value=\"0x04\">Short - Short - Medium</option>\n"
    "     <option value=\"0x05\">Short x4 - Medium - Short</option>\n"
    "     <option value=\"0x06\">Short x3 - Medium x3 - Short x3</option>\n"
    "     <option value=\"0x07\">Extra Long (XL)</option>\n"
    "     <option value=\"0x08\">Extra Short x6 (XS6)</option>\n"
    "     <option value=\"0x09\">Short Alternate (S-ALT)</option>\n"
    "     <option value=\"0x0A\">Medium (M)</option>\n"
    "     <option value=\"0x0B\">Long (L)</option>\n"
    "   </select>\n"

    "   <button onclick=\"submitCustomColour()\">Fill Custom-Colour</button>\n"
    "   <button onclick=\"OFF()\">OFF</button>\n"
    "   <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"


     " <div id=\"corners\" class=\"panel\">\n"
    "   <h2>[ Corners Controls ]</h2>\n"

    "   <label for=\"cornerCentre\">Centre Colour:</label>\n"
    "   <select id=\"cornerCentre\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"cornerA\">Corner A:</label>\n"
    "   <select id=\"cornerA\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"

    "   <label for=\"cornerB\">Corner B:</label>\n"
    "   <select id=\"cornerB\">\n"
    "     <option value=\"0x00\">Cyan</option>\n"
    "     <option value=\"0x01\">Purple</option>\n"
    "     <option value=\"0x02\">Blue</option>\n"
    "     <option value=\"0x03\">Midnight Blue</option>\n"
    "     <option value=\"0x05\">Bright Purple</option>\n"
    "     <option value=\"0x06\">Lavender</option>\n"
    "     <option value=\"0x08\">Pink</option>\n"
    "     <option value=\"0x0F\">Yellow / Orange</option>\n"
    "     <option value=\"0x10\">Off Yellow</option>\n"
    "     <option value=\"0x12\">Lime</option>\n"
    "     <option value=\"0x13\">Orange</option>\n"
    "     <option value=\"0x14\">Red / Orange</option>\n"
    "     <option value=\"0x15\">Red</option>\n"
    "     <option value=\"0x19\">Green</option>\n"
    "     <option value=\"0x1A\">Lime Green</option>\n"
    "     <option value=\"0x1B\">White</option>\n"
    "     <option value=\"0x1D\">Off</option>\n"
    "     <option value=\"0x1F\" selected>Random</option>\n"
    "   </select>\n"
    "   <label for=\"cornerVib\">Vibration:</label>\n"
    "   <select id=\"cornerVib\">\n"
    "     <option value=\"0x00\">None (Off)</option>\n"
    "     <option value=\"0x01\">Short (S)</option>\n"
    "     <option value=\"0x02\">Short - Short (S-S)</option>\n"
    "     <option value=\"0x03\">Short x3 (S-S-S)</option>\n"
    "     <option value=\"0x04\">Short - Short - Medium</option>\n"
    "     <option value=\"0x05\">Short x4 - Medium - Short</option>\n"
    "     <option value=\"0x06\">Short x3 - Medium x3 - Short x3</option>\n"
    "     <option value=\"0x07\">Extra Long (XL)</option>\n"
    "     <option value=\"0x08\">Extra Short x6 (XS6)</option>\n"
    "     <option value=\"0x09\">Short Alternate (S-ALT)</option>\n"
    "     <option value=\"0x0A\">Medium (M)</option>\n"
    "     <option value=\"0x0B\">Long (L)</option>\n"
    "   </select>\n"
    "<div class='slidecontainer'>"
    "<input type='range' min='1' max='255' value='50' class='slider' id='cornermyRange'>"
    "</div>"

    "   <button onclick=\"submitCornerColour()\">Fill Corners</button>\n"
    " <button onclick=\"OFF()\">OFF</button>\n"
    " <button onclick=\"WAKE()\">WAKE</button>\n"
    " </div>\n"


    " <div id=\"effects\" class=\"panel\">\n"
    " <label for=\"effectSelect\">Effect Type:</label>\n"
    " <select id=\"effectSelect\">\n"
    " <option value=\"rainbow\">Rainbow</option>\n"
    " <option value=\"circle\">Circle</option>\n"
    " </select>\n"
    " <button onclick=\"submitEffects()\">Run Effect</button>\n"
    " </div>\n"
    " <div id=\"statusBox\" class=\"status-msg\"></div>\n"
    "</div>\n"
    "<script>\n"
    "const redSlider = document.getElementById('red');\n"
    "const greenSlider = document.getElementById('green');\n"
    "const blueSlider = document.getElementById('blue');\n"

    "const redVal = document.getElementById('redVal');\n"
    "const greenVal = document.getElementById('greenVal');\n"
    "const blueVal = document.getElementById('blueVal');\n"

    "const colorBox = document.getElementById('colorBox');\n"
    "const rgbText = document.getElementById('rgbValue');\n"

    "function updateColor() {\n"
    "  const r = redSlider.value;\n"
    "  const g = greenSlider.value;\n"
    "  const b = blueSlider.value;\n"

    "  redVal.textContent = r;\n"
    "  greenVal.textContent = g;\n"
    "  blueVal.textContent = b;\n"

    "  const rgbColor = `rgb(${r}, ${g}, ${b})`;\n"
    "  colorBox.style.backgroundColor = rgbColor;\n"
    "  rgbText.textContent = rgbColor;\n"
    "}\n"

    "redSlider.addEventListener('input', updateColor);\n"
    "greenSlider.addEventListener('input', updateColor);\n"
    "blueSlider.addEventListener('input', updateColor);\n"

    "updateColor();\n"

    " function switchPanel(panelId) {\n"
    "   document.querySelectorAll('.panel').forEach(panel => panel.classList.remove('active'));\n"
    "   document.getElementById(panelId).classList.add('active');\n"
    " }\n"
    " function showStatus(message, isError = false) {\n"
    "   const statusBox = document.getElementById('statusBox');\n"
    "   statusBox.textContent = message;\n"
    "   statusBox.className = 'status-msg ' + (isError ? 'error' : 'success');\n"
    "   statusBox.style.display = 'block';\n"
    "   setTimeout(() => { statusBox.style.display = 'none'; }, 3000);\n"
    " }\n"
    " function submitSingle() {\n"
    "   const colour = document.getElementById('mbColour').value;\n"
    "   const vibration = document.getElementById('vibPattern').value;\n"
    "   const mask = document.getElementById('ledMask').value;\n"
    "   const url = \`/api/single?colour=${encodeURIComponent(colour)}&vib=${encodeURIComponent(vibration)}&mask=${encodeURIComponent(mask)}\`;\n"
    "   fetch(url)\n"
    "     .then(res => res.ok ? showStatus(\"LED settings saved!\") : showStatus(\"Failed to save LED settings\", true))\n"
    "     .catch(() => showStatus(\"Network error\", true));\n"
    " }\n"
    " function submitEffects() {\n"
    "   const effect = document.getElementById('effectSelect').value;\n"
    "   fetch(\`/api/single?band=${encodeURIComponent(effect)}\`)\n"
    "     .then(res => res.ok ? showStatus(\"Effect triggered!\") : showStatus(\"Failed\", true))\n"
    "     .catch(() => showStatus(\"Network error\", true));\n"
    " }\n"
    " function submitMultiColour() {\n"
    "   const centre = parseInt(document.getElementById('multiCentre').value, 16);\n"
    "   const topLeft = parseInt(document.getElementById('multiTopLeft').value, 16);\n"
    "   const topRight = parseInt(document.getElementById('multiTopRight').value, 16);\n"
    "   const bottomLeft = parseInt(document.getElementById('multiBottomLeft').value, 16);\n"
    "   const bottomRight = parseInt(document.getElementById('multiBottomRight').value, 16);\n"
    "   const vib = parseInt(document.getElementById('multiVib').value, 16);\n"
    "   const url = '/api/multicolour'\n"
    "       + '?centre=' + centre\n"
    "       + '&topright=' + topRight\n"
    "       + '&bottomright=' + bottomRight\n"
    "       + '&topleft=' + topLeft\n"
    "       + '&bottomleft=' + bottomLeft\n"
    "       + '&vib=' + vib;\n"
    "\n"
    "   fetch(url)\n"
    "     .then(res => res.ok\n"
    "       ? showStatus('Multi-colour sent!')\n"
    "       : showStatus('Failed to send multi-colour', true))\n"
    "     .catch(() => showStatus('Network error', true));\n"
    " }\n"
    

     " function submitFlickerColour() {\n"
    "   const centre = parseInt(document.getElementById('flickerCentre').value, 16);\n"
    "   const topLeft = parseInt(document.getElementById('flickerTopLeft').value, 16);\n"
    "   const topRight = parseInt(document.getElementById('flickerTopRight').value, 16);\n"
    "   const bottomLeft = parseInt(document.getElementById('flickerBottomLeft').value, 16);\n"
    "   const bottomRight = parseInt(document.getElementById('flickerBottomRight').value, 16);\n"
    "   const vib = parseInt(document.getElementById('flickerVib').value, 16);\n"
    "   const speed = document.getElementById('flickermyRange').value;\n"
    "   const url = '/api/multicolour'\n"
    "       + '?flickercentre=' + centre\n"
    "       + '&flickertopright=' + topRight\n"
    "       + '&flickerbottomright=' + bottomRight\n"
    "       + '&flickertopleft=' + topLeft\n"
    "       + '&flickerbottomleft=' + bottomLeft\n"
    "       + '&flickerspeed=' + speed\n"
    "       + '&flickervib=' + vib;\n"
    "\n"
    "   fetch(url)\n"
    "     .then(res => res.ok\n"
    "       ? showStatus('Multi-colour sent!')\n"
    "       : showStatus('Failed to send multi-colour', true))\n"
    "     .catch(() => showStatus('Network error', true));\n"
    " }\n"



    " function submitCornerColour() {\n"
    "   const centre = parseInt(document.getElementById('multiCentre').value, 16);\n"
    "   const cornerA = parseInt(document.getElementById('cornerA').value, 16);\n"
    "   const cornerB = parseInt(document.getElementById('cornerB').value, 16);\n"
    "   const vib = parseInt(document.getElementById('multiVib').value, 16);\n"
    "   const speed = document.getElementById('cornermyRange').value;\n"
    "   const url = '/api/multicolour'\n"
    "       + '?cornercentre=' + centre\n"
    "       + '&cornerA=' + cornerA\n"
    "       + '&cornerB=' + cornerB\n"
    "       + '&cornerspeed=' + speed\n"
    "       + '&cornervib=' + vib;\n"
    "\n"
    "   fetch(url)\n"
    "     .then(res => res.ok\n"
    "       ? showStatus('Multi-colour sent!')\n"
    "       : showStatus('Failed to send multi-colour', true))\n"
    "     .catch(() => showStatus('Network error', true));\n"
    " }\n"

    " function submitDualColour() {\n"
    "   const centre = parseInt(document.getElementById('dualCentre').value, 16);\n"
    "   const outer = parseInt(document.getElementById('dualOuter').value, 16);\n"
    "   const vib = parseInt(document.getElementById('dualVib').value, 16);\n"
    "\n"
    "   const url = '/api/dualcolour'\n"
    "       + '?dualcentre=' + centre\n"
    "       + '&dualouter=' + outer\n"
    "       + '&dualvib=' + vib;\n"
    "\n"
    "   fetch(url)\n"
    "     .then(res => res.ok\n"
    "       ? showStatus('Dual-colour sent!')\n"
    "       : showStatus('Failed to send dual-colour', true))\n"
    "     .catch(() => showStatus('Network error', true));\n"
    " }\n"
    " function submitCrossfade() {\n"
    "   const centre = parseInt(document.getElementById('CrossfadeColourA').value, 16);\n"
    "   const outer = parseInt(document.getElementById('CrossfadeColourB').value, 16);\n"
    "   const vib = parseInt(document.getElementById('CrossfadeVib').value, 16);\n"
    "  const speed = document.getElementById('myRange').value;\n"
    "\n"
    "   const url = '/api/crossfade'\n"
    "       + '?crossfadecoloura=' + centre\n"
    "       + '&crossfadecolourb=' + outer\n"
    "       + '&crossfadevib=' + vib\n"
    "       + '&crossfadespeed=' + speed;\n"
    "\n"
    "   fetch(url)\n"
    "     .then(res => res.ok\n"
    "       ? showStatus('Crossfade sent!')\n"
    "       : showStatus('Failed to send crossfade', true))\n"
    "     .catch(() => showStatus('Network error', true));\n"
    " }\n"
    " function submitCustomColour() {\n"
    "   const red = parseInt(document.getElementById('red').value, 10);\n"
    "   const green = parseInt(document.getElementById('green').value, 10);\n"
    "   const blue = parseInt(document.getElementById('blue').value, 10);\n"
    "   const vib = parseInt(document.getElementById('CustomVib').value, 16);\n"
    "   const url = '/api/customcolour'\n"
    "       + '?red=' + red\n"
    "       + '&green=' + green\n"
    "       + '&blue=' + blue\n"
    "       + '&customvib=' + vib;\n"
    "\n"
    "   fetch(url)\n"
    "     .then(res => res.ok\n"
    "       ? showStatus('Custom colour sent!')\n"
    "       : showStatus('Failed to send custom colour', true))\n"
    "     .catch(() => showStatus('Network error', true));\n"
    " }\n"
    " function OFF() {\n"
    "   fetch(\`/api/single?colour=0x1D&vib=0x00&mask=0x00\`)\n"
    "     .then(res => res.ok ? showStatus(\"Turned Off!\") : showStatus(\"Failed to send command\", true))\n"
    "     .catch(() => showStatus(\"Network error\", true));\n"
    " }\n"
    " function WAKE() {\n"
    "   fetch(\`/api/single?band=connect\`)\n"
    "     .then(res => res.ok ? showStatus(\"Wake packet sent!\") : showStatus(\"Failed to send command\", true))\n"
    "     .catch(() => showStatus(\"Network error\", true));\n"
    " }\n"
    "</script>\n"
    "</body>\n"
    "</html>";


#endif